name: build oses
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - oses/**
jobs:
  push:
    name: "stanlystark:${{ matrix.oses }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        oses:
          - debian_bookworm
        include:
          - oses: debian_bookworm
            alias_tags: |
              ghcr.io/gobackup-egg/stanlystark:debian
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./oses/${{ matrix.oses }}
          file: ./oses/${{ matrix.oses }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/stanlystark/os:${{ matrix.oses }}
            ${{ matrix.alias_tags }}
